modLoader = "kotlinforforge"
loaderVersion = "[4.10,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
logoFile = "logo.png"
description = '''This mod allows you to enchant various blocks added with Create.'''

[[dependencies.${mod_id}]]
modId = "create"
mandatory = true
versionRange = "[0.5.1.f,)"
ordering = "NONE"
side = "BOTH"
