[versions]
kotlin = "2.0.0"
loom = "1.13-SNAPSHOT"
architecturyPlugin = "3.4-SNAPSHOT"
shadow = "8.1.1"
minecraft = "1.20.1"
parchiment = "2023.09.03@zip"
forge = "1.20.1-47.4.15"
forgeKotlin = "4.12.0"
fabricLoader = "0.18.4"
fabricApi = "0.92.2+1.20.1"
fabricKotlin = "1.11.0+kotlin.2.0.0"
architectury = "9.2.14"
createForge = "6.0.8-289"
createFabric = "6.0.8.1+build.1744-mc1.20.1"
flywheel = "1.0.5"
registrate = "MC1.20-1.3.3"
majruszLibForge = "5302100"
majruszLibFabric = "5301915"
modMenu = "7.2.2"
koin = "3.5.6"
modPublisher = "2.1.6"
zenith = "1.2.4-1.20.1"
ponder = "1.0.91"

[libraries]
minecraft = { module = "net.minecraft:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.20.1", version.ref = "parchiment" }
forge = { module = "net.minecraftforge:forge", version.ref = "forge" }
forge-kotlin = { module = "thedarkcolour:kotlinforforge", version.ref = "forgeKotlin" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabricLoader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabricApi" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabricKotlin" }
create-forge = { module = "com.simibubi.create:create-1.20.1", version.ref = "createForge" }
create-fabric = { module = "com.simibubi.create:create-fabric", version.ref = "createFabric" }
flywheel-forge-api = { module = "dev.engine-room.flywheel:flywheel-forge-api-1.20.1", version.ref = "flywheel" }
flywheel-forge = { module = "dev.engine-room.flywheel:flywheel-forge-1.20.1", version.ref = "flywheel" }
flywheel-fabric-api = { module = "dev.engine-room.flywheel:flywheel-fabric-api-1.20.1", version.ref = "flywheel" }
flywheel-fabric = { module = "dev.engine-room.flywheel:flywheel-fabric-1.20.1", version.ref = "flywheel" }
registrate = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
ponder-common = { module = "net.createmod.ponder:Ponder-Common-1.20.1", version.ref = "ponder" }
ponder-forge = { module = "net.createmod.ponder:Ponder-Forge-1.20.1", version.ref = "ponder" }
ponder-fabric = { module = "net.createmod.ponder:Ponder-Fabric-1.20.1", version.ref = "ponder" }
majrusz-library-forge = { module = "curse.maven:majrusz-library-437409", version.ref = "majruszLibForge" }
majrusz-library-fabric = { module = "curse.maven:majrusz-library-437409", version.ref = "majruszLibFabric" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modMenu" }
koin = { module = "io.insert-koin:koin-core-jvm", version.ref = "koin" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "dev.architectury.loom", version.ref = "loom" }
architectury = { id = "architectury-plugin", version.ref = "architecturyPlugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
modPublisher = { id = "com.hypherionmc.modutils.modpublisher", version.ref = "modPublisher" }
