name: Upload to CurseForge and Modrinth
on:
  push:
    branches:
      - 1.20.1

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      CURSE_FORGE_API_KEY: ${{ secrets.CURSE_FORGE_API_KEY }}
      MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build jar
        run: ./gradlew build

      - name: Upload Forge version
        run: ./gradlew forge:publishMod

      - name: Upload Fabric version
        run: ./gradlew fabric:publishMod
